//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CesionesPago.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class xuconfig
    {
        public string ef_cve { get; set; }
        public bool sw_multusr { get; set; }
        public string server_rpt { get; set; }
        public string sol_ver { get; set; }
        public string sw_concom { get; set; }
        public string sw_convta { get; set; }
        public bool sw_alm { get; set; }
        public bool sw_ef { get; set; }
        public bool sw_ivainc { get; set; }
        public bool sw_ivacinc { get; set; }
        public bool sw_comis { get; set; }
        public bool sw_ieps { get; set; }
        public bool sw_costra { get; set; }
        public bool sw_cosxart { get; set; }
        public short num_decuns { get; set; }
        public short num_decimp { get; set; }
        public bool sw_faclote { get; set; }
        public bool sw_cancped { get; set; }
        public bool sw_2damon { get; set; }
        public bool sw_tmdef { get; set; }
        public bool sw_digver { get; set; }
        public short mes_inieje { get; set; }
        public bool sw_inst { get; set; }
        public System.DateTime fec_actual { get; set; }
        public string id_ultact { get; set; }
        public short anio_act { get; set; }
        public short mes_act { get; set; }
        public string drive_bkup { get; set; }
        public string drive_pdv { get; set; }
        public short num_sesabr { get; set; }
        public short dias_gracia { get; set; }
        public decimal pct_retenc { get; set; }
        public Nullable<short> num_decpre { get; set; }
        public Nullable<double> saldo_max { get; set; }
        public Nullable<double> otro1 { get; set; }
        public Nullable<double> otro2 { get; set; }
        public Nullable<double> otro3 { get; set; }
        public Nullable<double> otro4 { get; set; }
        public Nullable<double> otro5 { get; set; }
        public string eanprov { get; set; }
        public string eanfol { get; set; }
        public string tm { get; set; }
        public string server_cat { get; set; }
    }
}
