//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CesionesPago.Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CesionesEntities : DbContext
    {
        public CesionesEntities()
            : base("name=CesionesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<xcdconapl_cl> xcdconapl_cl { get; set; }
        public virtual DbSet<xcuser> xcuser { get; set; }
    
        public virtual ObjectResult<WebAppConsultaPagos_Result> WebAppConsultaPagos(string ef_cve, Nullable<int> num_fol)
        {
            var ef_cveParameter = ef_cve != null ?
                new ObjectParameter("ef_cve", ef_cve) :
                new ObjectParameter("ef_cve", typeof(string));
    
            var num_folParameter = num_fol.HasValue ?
                new ObjectParameter("num_fol", num_fol) :
                new ObjectParameter("num_fol", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WebAppConsultaPagos_Result>("WebAppConsultaPagos", ef_cveParameter, num_folParameter);
        }
    
        public virtual ObjectResult<WebAppCesionesPago_Result> WebAppCesionesPago(string ef_cve, Nullable<int> tipoCesion, string tipDoc, Nullable<int> num_fol, Nullable<System.DateTime> fec_mov, string user_cve)
        {
            var ef_cveParameter = ef_cve != null ?
                new ObjectParameter("ef_cve", ef_cve) :
                new ObjectParameter("ef_cve", typeof(string));
    
            var tipoCesionParameter = tipoCesion.HasValue ?
                new ObjectParameter("tipoCesion", tipoCesion) :
                new ObjectParameter("tipoCesion", typeof(int));
    
            var tipDocParameter = tipDoc != null ?
                new ObjectParameter("tipDoc", tipDoc) :
                new ObjectParameter("tipDoc", typeof(string));
    
            var num_folParameter = num_fol.HasValue ?
                new ObjectParameter("num_fol", num_fol) :
                new ObjectParameter("num_fol", typeof(int));
    
            var fec_movParameter = fec_mov.HasValue ?
                new ObjectParameter("fec_mov", fec_mov) :
                new ObjectParameter("fec_mov", typeof(System.DateTime));
    
            var user_cveParameter = user_cve != null ?
                new ObjectParameter("user_cve", user_cve) :
                new ObjectParameter("user_cve", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WebAppCesionesPago_Result>("WebAppCesionesPago", ef_cveParameter, tipoCesionParameter, tipDocParameter, num_folParameter, fec_movParameter, user_cveParameter);
        }
    
        public virtual ObjectResult<WebAppCesionesConfirming_Result> WebAppCesionesConfirming(Nullable<short> sw, string ef_cve)
        {
            var swParameter = sw.HasValue ?
                new ObjectParameter("sw", sw) :
                new ObjectParameter("sw", typeof(short));
    
            var ef_cveParameter = ef_cve != null ?
                new ObjectParameter("ef_cve", ef_cve) :
                new ObjectParameter("ef_cve", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WebAppCesionesConfirming_Result>("WebAppCesionesConfirming", swParameter, ef_cveParameter);
        }
    }
}
